//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.22 at 02:32:05 PM CEST 
//


package hr.aportolan.kps.provisioning.notification;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.aportolan.kps.provisioning.notification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.aportolan.kps.provisioning.notification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifyProvisioningStateRequestType }
     * 
     */
    public NotifyProvisioningStateRequestType createNotifyProvisioningStateRequestType() {
        return new NotifyProvisioningStateRequestType();
    }

    /**
     * Create an instance of {@link NotifyProvisioningStateResponseType }
     * 
     */
    public NotifyProvisioningStateResponseType createNotifyProvisioningStateResponseType() {
        return new NotifyProvisioningStateResponseType();
    }

    /**
     * Create an instance of {@link FaultMessageType }
     * 
     */
    public FaultMessageType createFaultMessageType() {
        return new FaultMessageType();
    }

}
