//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 07:03:02 AM CEST 
//

package hr.aportolan.kps.provisioning.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the hr.aportolan.kps.provisioning.ws package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _CancelProvisioningResponseType_QNAME = new QName("http://localhost:8080/schema/gen/ProvisioningOperationsSchema.xsd",
			"CancelProvisioningResponse");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: hr.aportolan.kps.provisioning.ws
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ProvisioningStateResponse }
	 * 
	 */
	public ProvisioningStateResponse createProvisioningStateResponseType() {
		return new ProvisioningStateResponse();
	}

	/**
	 * Create an instance of {@link ProvisioningStateRequest }
	 * 
	 */
	public ProvisioningStateRequest createProvisioningStateRequestType() {
		return new ProvisioningStateRequest();
	}

	/**
	 * Create an instance of {@link ProvisionSubscriberRequest }
	 * 
	 */
	public ProvisionSubscriberRequest createProvisionSubscriberRequestType() {
		return new ProvisionSubscriberRequest();
	}

	/**
	 * Create an instance of {@link Subscriber }
	 * 
	 */
	public Subscriber createSubscriber() {
		return new Subscriber();
	}

	/**
	 * Create an instance of {@link ProvisionSubscriberResponse }
	 * 
	 */
	public ProvisionSubscriberResponse createProvisionSubscriberResponseType() {
		return new ProvisionSubscriberResponse();
	}

	/**
	 * Create an instance of {@link FaultMessage }
	 * 
	 */
	public FaultMessage createFaultMessageType() {
		return new FaultMessage();
	}

	/**
	 * Create an instance of {@link CancelProvisioningRequest }
	 * 
	 */
	public CancelProvisioningRequest createCancelProvisioningRequestType() {
		return new CancelProvisioningRequest();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://localhost:8080/schema/gen/ProvisioningOperationsSchema.xsd", name = "CancelProvisioningResponseType")
	public JAXBElement<Object> createCancelProvisioningResponseType(Object value) {
		return new JAXBElement<Object>(_CancelProvisioningResponseType_QNAME, Object.class, null, value);
	}

}
