//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.24 at 02:17:27 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://aportolan.hr/kps/provisioning/ws")
package hr.aportolan.kps.provisioning.ws;
