//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 07:03:02 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kps-aportolan.rhcloud.com/schema/ProvisioningNotificationSchema", elementFormDefault = XmlNsForm.QUALIFIED)
package hr.aportolan.kps.provisioning.ws.client;

import javax.xml.bind.annotation.XmlNsForm;
